language: php

php:
  - 5.5
  - 5.6
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

services:
  - couchdb

env:
  matrix:
    - SCRIPT='modules/relaxed/tests/bin/drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/drupal-to-couchdb.sh'
    - SCRIPT='modules/relaxed/tests/bin/drupal-to-couchdb-non-admin.sh'
    - SCRIPT='modules/relaxed/tests/bin/couchdb-to-drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/couchdb-to-drupal-non-admin.sh'
    - SCRIPT='modules/relaxed/tests/bin/couchdb-to-drupal-php.sh'
    - SCRIPT='modules/relaxed/tests/bin/drupal-to-drupal.sh'
    - SCRIPT='modules/relaxed/tests/bin/pouchdb.sh'
    - SCRIPT='modules/relaxed/tests/bin/pouchdb-non-admin.sh'
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  # Update Composer so that the Drush installation doesn't fail.
  - composer selfupdate
  - mysql -e "create database IF NOT EXISTS drupal2;" -uroot

install:
  - sudo apt-get update
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Add always_populate_raw_post_data=-1 to php.ini.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Set up PHP-FPM.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Set up the Apache vhost for the first Drupal instance.
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_SERVERNAME%?drupal.loc?g" --in-place /etc/apache2/sites-available/default
  - echo "127.0.0.1 drupal.loc" | sudo tee -a /etc/hosts

  # Set up the Apache vhost for the second Drupal instance.
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/drupal2
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal2?g" --in-place /etc/apache2/sites-available/drupal2
  - sudo sed -e "s?%TRAVIS_BUILD_SERVERNAME%?drupal2.loc?g" --in-place /etc/apache2/sites-available/drupal2
  - sudo sed -i "/FastCgiExternalServer/d" --in-place /etc/apache2/sites-available/drupal2
  - echo "127.0.0.1 drupal2.loc" | sudo tee -a /etc/hosts

  - sudo a2ensite drupal2
  - sudo service apache2 restart

  # Install Drush.
  - export PATH=$PATH:/home/travis/.composer/vendor/bin
  - composer global require drush/drush:dev-master

before_script:
  # Try to prevent Mysql has gone away.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"

  # Checkout a directory structure with all dependencies.
  - git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-key_value.git $TRAVIS_BUILD_DIR/../drupal/modules/key_value
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-multiversion.git $TRAVIS_BUILD_DIR/../drupal/modules/multiversion
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/relaxed

  # Install the site that will host our tests.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal standard
  # Create the private directory.
  - sudo mkdir sites/default/files/private
  - sudo chmod 777 -R sites/default/files
  - sudo chmod 0664 sites/default/settings.php
  - sudo echo -e "$a\$settings['file_private_path'] = 'sites/default/files/private';" >> sites/default/settings.php
  # Enable Simpletest
  - drush en --yes simpletest

  # Checkout second directory structure with all dependencies.
  - git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal2
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-key_value.git $TRAVIS_BUILD_DIR/../drupal2/modules/key_value
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-multiversion.git $TRAVIS_BUILD_DIR/../drupal2/modules/multiversion
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal2/modules/relaxed

  # Install the site that will be used for Drupal-to-Drupal replication.
  - cd $TRAVIS_BUILD_DIR/../drupal2
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --verbose --yes site-install --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal2 standard
  # Create the private directory.
  - sudo mkdir sites/default/files/private
  - sudo chmod 777 -R sites/default/files
  - sudo chmod 0664 sites/default/settings.php
  - sudo echo -e "$a\$settings['file_private_path'] = 'sites/default/files/private';" >> sites/default/settings.php
  # Enable Simpletest
  - drush en --yes simpletest

script:
  - cd $TRAVIS_BUILD_DIR/../drupal
  - bash $SCRIPT
